---
title: "05_Functional"
author: "Elsa"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
## Functional differences

genome_counts_gift <- genome_counts_filt[genome_counts_filt$genome %in% rownames(genome_gifts), ]

common_samples <- intersect(
  sample_metadata$DNA_datasets,
  colnames(genome_counts_gift)
)

genome_counts_gift <- genome_counts_gift %>%
  select(genome, all_of(common_samples)) %>%
  column_to_rownames("genome") %>%
  filter(rowSums(. != 0, na.rm = TRUE) > 0) %>%
  select_if(~ !all(. == 0)) %>%
  rownames_to_column("genome")

genome_gifts_filt <- genome_gifts[rownames(genome_gifts) %in% genome_counts_gift$genome, ]
genome_gifts_filt <- genome_gifts_filt[, colSums(genome_gifts_filt != 0) > 0]
```

```{r}
# Aggregate bundle-level GIFTs into element level
GIFTs_elements <- to.elements(genome_gifts_filt, GIFT_db)

GIFTs_elements_filtered <- GIFTs_elements[
  rownames(GIFTs_elements) %in% genome_counts_gift$genome,
]

GIFTs_elements_filtered <- as.data.frame(GIFTs_elements_filtered) %>%
  select_if(~ !is.numeric(.) || sum(.) != 0)

# Aggregate element-level GIFTs into function level
GIFTs_functions <- to.functions(GIFTs_elements_filtered, GIFT_db)

# Aggregate function-level GIFTs into domains
GIFTs_domains <- to.domains(GIFTs_functions, GIFT_db)
```

```{r}
# Community-weighted average GIFTs per sample
genome_counts_row <- genome_counts_gift %>%
  mutate_at(vars(-genome), ~ . / sum(.)) %>%
  column_to_rownames("genome")

GIFTs_elements_community <- to.community(GIFTs_elements_filtered, genome_counts_row, GIFT_db)
GIFTs_functions_community <- to.community(GIFTs_functions, genome_counts_row, GIFT_db)
GIFTs_domains_community <- to.community(GIFTs_domains, genome_counts_row, GIFT_db)
```

```{r}
MCI <- GIFTs_functions_community %>%
  rowMeans() %>%
  as_tibble(rownames = "sample") %>%
  left_join(sample_metadata, by = join_by(sample == DNA_datasets)) %>%
  mutate(water_temp = factor(water_temp, levels = c(10, 20)))
```

```{r}
MCI %>%
  group_by(water_temp) %>%
  summarise(
    mean = round(mean(value, na.rm = TRUE), 3),
    sd = round(sd(value, na.rm = TRUE), 3),
    .groups = "drop"
  ) %>%
  mutate(MCI = str_c(mean, " +/- ", sd)) %>%
  select(water_temp, MCI) %>%
  rename("Water Temp" = water_temp) %>%
  tt()
```

```{r}
shapiro.test(residuals(lm(value ~ water_temp, data = MCI)))
bartlett.test(value ~ water_temp, data = MCI)

wilcox.test(value ~ water_temp, data = MCI)
```
```{r}
function_matrix <- GIFTs_functions_community %>%
  as.data.frame() %>%
  as.matrix()

metadata <- sample_metadata %>%
  select(DNA_datasets, water_temp) %>%
  mutate(water_temp = factor(water_temp, levels = c(10, 15, 20))) %>%
  column_to_rownames("DNA_datasets")

metadata <- metadata[rownames(function_matrix), , drop = FALSE]

stopifnot(all(rownames(function_matrix) %in% rownames(metadata)))
stopifnot(all(rownames(function_matrix) == rownames(metadata)))

adonis2(
  function_matrix ~ water_temp,
  data = metadata,
  method = "euclidean",
  permutations = 999
)
```

```{r}
element_gift <- GIFTs_elements_community %>%
  as.data.frame() %>%
  rownames_to_column("sample") %>%
  left_join(
    sample_metadata %>%
      select(DNA_datasets, water_temp) %>%
      mutate(water_temp = factor(water_temp, levels = c(10, 15, 20))),
    by = join_by(sample == DNA_datasets)
  )
```

```{r}
uniqueGIFT_db <- unique(GIFT_db[c(2, 4, 5, 6)]) %>%
  unite("Function", Function:Element, sep = "_", remove = FALSE)
```

```{r}
significant_elements <- element_gift %>%
  pivot_longer(
    -c(sample, water_temp),
    names_to = "trait",
    values_to = "value"
  ) %>%
  group_by(trait) %>%
  summarise(
    p_value = kruskal.test(value ~ water_temp)$p.value,
    .groups = "drop") %>%
  mutate(p_adjust = p.adjust(p_value, method = "BH")) %>%
  filter(p_adjust < 0.05)
```
```{r}
selected_data <- element_gift %>%
  pivot_longer(
    -c(sample, water_temp),
    names_to = "trait",
    values_to = "value"
  ) %>%
  filter(trait %in% significant_elements$trait)
```

```{r}
pairwise_results <- selected_data %>%
  group_by(trait) %>%
  wilcox_test(value ~ water_temp, p.adjust.method = "BH") %>%
  ungroup() %>%
  filter(p < 0.05) %>%
  mutate(comparison = paste(group1, "vs", group2)) %>%
  left_join(uniqueGIFT_db, by = join_by(trait == Code_element))
```

```{r}
plot_elem <- ggplot(pairwise_results, aes(x = comparison, y = fct_rev(Function))) +
  geom_tile(aes(fill = p), color = "white") +
 # geom_text(aes(label = p.signif), size = 4, color = "black") +
  scale_fill_gradient(
    low = "#b30000",
    high = "#fef0d9",
    name = "p-value"
  ) +
  theme_minimal() +
  labs(
    title = "Significant Functional Differences by Water Temperature",
    x = "Water Temperature Comparison",
    y = "Trait"
  ) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    panel.grid = element_blank()
  )
```

```{r}
plot_data <- element_gift %>%
  pivot_longer(
    -c(sample, water_temp),
    names_to = "trait",
    values_to = "value"
  ) %>%
  filter(trait %in% pairwise_results$trait) %>%
  left_join(uniqueGIFT_db, by = join_by(trait == Code_element))
```
```{r}
plot_data %>%
  ggplot(aes(x = water_temp, y = value, fill = water_temp, color = water_temp)) +
  geom_boxplot(outlier.shape = NA, alpha = 0.7) +
  geom_jitter(width = 0.2, size = 1, alpha = 0.4) +
  facet_wrap(~ Function, scales = "free_y", ncol = 4) +
  theme_minimal() +
  theme(strip.text = element_text(size = 12)) +
  labs(
    x = "Water Temperature",
    y = "Community-weighted functional value",
    fill = "Water Temp",
    color = "Water Temp"
  )
```
```{r}
enrichment_results <- element_gift %>%
  pivot_longer(
    -c(sample, water_temp),
    names_to = "trait",
    values_to = "value"
  ) %>%
  filter(trait %in% pairwise_results$trait) %>%
  group_by(trait) %>%
  summarise(
    median_10C = median(value[water_temp == "10"], na.rm = TRUE),
    median_20C = median(value[water_temp == "20"], na.rm = TRUE),
    log2FC = log2((median_20C + 1) / (median_10C + 1)),
    difference = median_20C - median_10C,
    .groups = "drop"
  )
```
```{r}
enrichment_code <- enrichment_results %>%
  left_join(unique(GIFT_db[c(2, 3, 4, 5, 6)]), by = join_by(trait == Code_element))
```
```{r}
enrichment_code %>%
  ggplot(aes(x = forcats::fct_reorder(Function, log2FC), y = log2FC)) +
  geom_col(fill = "grey50") +
  geom_hline(yintercept = 0) +
  coord_flip() +
  theme_classic() +
  labs(
    x = "Microbial Functional Capacity",
    y = "log2FC: 20C vs 10C"
  )
```
#Functional Difference Comparisons

```{r}
element_gift_edited <- GIFTs_elements_community %>%
  as.data.frame() %>%
  rownames_to_column("sample") %>%
  left_join(
    sample_metadata %>%
      select(DNA_datasets, water_temp, sampling_date, experimental_group) %>%
      mutate(water_temp = factor(water_temp, levels = c(10, 15, 20))),
    by = join_by(sample == DNA_datasets)
  )
```

```{r}
uniqueGIFT_db <- unique(GIFT_db[c(2, 4, 5, 6)]) %>%
  unite("Function", Function:Element, sep = "_", remove = FALSE)
```

```{r}
significant_elements_pre <- element_gift_edited %>%
  pivot_longer(
    -c(sample, water_temp, sampling_date, experimental_group),
    names_to = "trait",
    values_to = "value"
  ) %>%
  filter(sampling_date <= as.Date("2025-08-30")) %>%
  group_by(trait) %>%
  summarise(
    p_value = kruskal.test(value ~ water_temp)$p.value,
    .groups = "drop") %>%
  mutate(p_adjust = p.adjust(p_value, method = "BH")) 

significant_elements_post <- element_gift_edited %>%
  pivot_longer(
    -c(sample, water_temp, sampling_date, experimental_group),
    names_to = "trait",
    values_to = "value"
  ) %>%
  group_by(trait) %>%
  filter(sampling_date >= as.Date("2025-08-30")) %>%
  summarise(
    p_value = kruskal.test(value ~ water_temp)$p.value,
    .groups = "drop") %>%
  mutate(p_adjust = p.adjust(p_value, method = "BH")) 
```
  
```{r}
selected_data_pre <- element_gift_edited %>%
  filter(sampling_date <= as.Date("2025-08-30")) %>%
  pivot_longer(
    -c(sample, water_temp, sampling_date, experimental_group),
    names_to = "trait",
    values_to = "value"
  ) %>%
  filter(trait %in% significant_elements$trait)

selected_data_post <- element_gift_edited %>%
  filter(sampling_date >= as.Date("2025-08-30")) %>%
  pivot_longer(
    -c(sample, water_temp, sampling_date, experimental_group),
    names_to = "trait",
    values_to = "value"
  ) %>%
  filter(trait %in% significant_elements$trait)
```

```{r}
pairwise_results_pre <- selected_data_pre %>%
  group_by(trait) %>%
  wilcox_test(value ~ water_temp, p.adjust.method = "BH") %>%
  ungroup() %>%
  filter(p < 0.05) %>%
  mutate(comparison = paste(group1, "vs", group2)) %>%
  left_join(uniqueGIFT_db, by = join_by(trait == Code_element))

pairwise_results_post <- selected_data_post %>%
  group_by(trait) %>%
  wilcox_test(value ~ water_temp, p.adjust.method = "BH") %>%
  ungroup() %>%
  filter(p < 0.05) %>%
  mutate(comparison = paste(group1, "vs", group2)) %>%
  left_join(uniqueGIFT_db, by = join_by(trait == Code_element))
```

#Pre-Treatment Functions
```{r}
plot_elem_pre <- ggplot(pairwise_results_pre, aes(x = comparison, y = fct_rev(Function))) +
  geom_tile(aes(fill = p), color = "white") +
 # geom_text(aes(label = p.signif), size = 4, color = "black") +
  scale_fill_gradient(
    low = "#b30000",
    high = "#fef0d9",
    name = "p-value"
  ) +
  theme_minimal() +
  labs(
    title = "Significant Functional Differences by Water Temperature",
    x = "Water Temperature Comparison",
    y = "Trait"
  ) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    panel.grid = element_blank()
  )
```

```{r}
plot_data_pre <- element_gift_edited %>%
  filter(sampling_date <= as.Date("2025-08-30")) %>%
  pivot_longer(
    -c(sample, water_temp, sampling_date, experimental_group),
    names_to = "trait",
    values_to = "value"
  ) %>%
  filter(trait %in% pairwise_results_pre$trait) %>%
  left_join(uniqueGIFT_db, by = join_by(trait == Code_element))
```
```{r}
plot_data_pre %>%
  ggplot(aes(x = water_temp, y = value, fill = water_temp, color = water_temp)) +
  geom_boxplot(outlier.shape = NA, alpha = 0.7) +
  geom_jitter(width = 0.2, size = 1, alpha = 0.4) +
  facet_wrap(~ Function, scales = "free_y", ncol = 4) +
  theme_minimal() +
  theme(strip.text = element_text(size = 12)) +
  labs(
    x = "Water Temperature",
    y = "Community-weighted functional value",
    fill = "Water Temp",
    color = "Water Temp"
  )
```

```{r}
enrichment_results_pre <- element_gift_edited %>%
  pivot_longer(
    -c(sample, water_temp, sampling_date, experimental_group),
    names_to = "trait",
    values_to = "value"
  ) %>%
  filter(trait %in% pairwise_results_pre$trait) %>%
  group_by(trait) %>%
  summarise(
    median_10C = median(value[water_temp == "10"], na.rm = TRUE),
    median_20C = median(value[water_temp == "20"], na.rm = TRUE),
    log2FC = log2((median_20C + 1) / (median_10C + 1)),
    difference = median_20C - median_10C,
    .groups = "drop"
  )
```
```{r}
enrichment_code <- enrichment_results_pre %>%
  left_join(unique(GIFT_db[c(2, 3, 4, 5, 6)]), by = join_by(trait == Code_element))
```
```{r}
enrichment_code %>%
  ggplot(aes(x = forcats::fct_reorder(Function, log2FC), y = log2FC)) +
  geom_col(fill = "grey50") +
  geom_hline(yintercept = 0) +
  coord_flip() +
  theme_classic() +
  labs(
    x = "Microbial Functional Capacity",
    y = "log2FC: 20C vs 10C"
  )
```

#Post-Treatment Functions
```{r}
plot_elem_post <- ggplot(pairwise_results_post, aes(x = comparison, y = fct_rev(Function))) +
  geom_tile(aes(fill = p), color = "white") +
 # geom_text(aes(label = p.signif), size = 4, color = "black") +
  scale_fill_gradient(
    low = "#b30000",
    high = "#fef0d9",
    name = "p-value"
  ) +
  theme_minimal() +
  labs(
    title = "Significant Functional Differences by Water Temperature",
    x = "Water Temperature Comparison",
    y = "Trait"
  ) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    panel.grid = element_blank()
  )
```

```{r}
plot_data_post <- element_gift_edited %>%
  filter(sampling_date >= as.Date("2025-08-30")) %>%
  pivot_longer(
    -c(sample, water_temp, sampling_date, experimental_group),
    names_to = "trait",
    values_to = "value"
  ) %>%
  filter(trait %in% pairwise_results_post$trait) %>%
  left_join(uniqueGIFT_db, by = join_by(trait == Code_element))
```
```{r}
plot_data_post %>%
  ggplot(aes(x = water_temp, y = value, fill = water_temp, color = water_temp)) +
  geom_boxplot(outlier.shape = NA, alpha = 0.7) +
  geom_jitter(width = 0.2, size = 1, alpha = 0.4) +
  facet_wrap(~ Function, scales = "free_y", ncol = 4) +
  theme_minimal() +
  theme(strip.text = element_text(size = 12)) +
  labs(
    x = "Water Temperature",
    y = "Community-weighted functional value",
    fill = "Water Temp",
    color = "Water Temp"
  )
```

```{r}
enrichment_results_post <- element_gift_edited %>%
  pivot_longer(
    -c(sample, water_temp, sampling_date, experimental_group),
    names_to = "trait",
    values_to = "value"
  ) %>%
  filter(trait %in% pairwise_results_post$trait) %>%
  group_by(trait) %>%
  summarise(
    median_10C = median(value[water_temp == "10"], na.rm = TRUE),
    median_20C = median(value[water_temp == "20"], na.rm = TRUE),
    log2FC = log2((median_20C + 1) / (median_10C + 1)),
    difference = median_20C - median_10C,
    .groups = "drop"
  )
```
```{r}
enrichment_code <- enrichment_results_post %>%
  left_join(unique(GIFT_db[c(2, 3, 4, 5, 6)]), by = join_by(trait == Code_element))
```
```{r}
enrichment_code %>%
  ggplot(aes(x = forcats::fct_reorder(Function, log2FC), y = log2FC)) +
  geom_col(fill = "grey50") +
  geom_hline(yintercept = 0) +
  coord_flip() +
  theme_classic() +
  labs(
    x = "Microbial Functional Capacity",
    y = "log2FC: 20C vs 10C"
  )
```

#Pre/Post Combined Comparison
```{r}
pairwise_results_combined <- bind_rows(
  pairwise_results_pre %>% mutate(experiment_phase = "pre-ABX"),
  pairwise_results_post %>% mutate(experiment_phase = "post-ABX"))

plot_elem_combined <- ggplot(pairwise_results_combined, aes(x = comparison, y = fct_rev(Function))) +
  geom_tile(aes(fill = p), color = "white") +
 # geom_text(aes(label = p.signif), size = 4, color = "black") +
  scale_fill_gradient(
    low = "#b30000",
    high = "#fef0d9",
    name = "p-value"
  ) +
  theme_minimal() +
  labs(
    title = "Significant Functional Differences by Water Temperature",
    x = "Water Temperature Comparison",
    y = "Trait"
  ) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    panel.grid = element_blank()
  )
```

```{r}
plot_data_combined <- element_gift_edited %>%
  pivot_longer(
    -c(sample, water_temp, sampling_date, experimental_group),
    names_to = "trait",
    values_to = "value"
  ) %>%
  filter(trait %in% pairwise_results_combined$trait) %>%
  left_join(uniqueGIFT_db, by = join_by(trait == Code_element))

plot_data_combined <- element_gift_edited %>%
  pivot_longer(
    -c(sample, water_temp, sampling_date, experimental_group),
    names_to = "trait",
    values_to = "value"
  ) %>%
  filter(trait %in% pairwise_results_combined$trait) %>%
  left_join(uniqueGIFT_db, by = join_by(trait == Code_element))

plot_data_combined <- bind_rows(
  plot_data_pre %>% mutate(experiment_phase = "pre-ABX"),
  plot_data_post %>% mutate(experiment_phase = "post-ABX")
)
```
```{r}
plot_data_combined %>%
  ggplot(aes(x = water_temp, y = value, fill = water_temp, color = water_temp)) +
  geom_boxplot(outlier.shape = NA, alpha = 0.7) +
  geom_jitter(width = 0.2, size = 1, alpha = 0.4) +
  facet_grid(Function ~ experiment_phase, scales = "free_y") + #Had to search this up to be able to add an experimental phase facet wrap without overriding the facet wrap line that was already in the code
  theme_minimal() +
  theme(strip.text = element_text(size = 12)) +
  labs(
    x = "Water Temperature",
    y = "Community-weighted functional value",
    fill = "Water Temp",
    color = "Water Temp"
  )
```

```{r}
enrichment_results_combined <- bind_rows(
  enrichment_results_pre %>% mutate(experiment_phase = "pre-ABX"),
  enrichment_results_post %>% mutate(experiment_phase = "post-ABX"))
```

```{r}
enrichment_code_combined <- enrichment_results_combined %>%
  left_join(unique(GIFT_db[c(2, 3, 4, 5, 6)]), by = join_by(trait == Code_element))
```
```{r}
enrichment_code_combined %>%
  ggplot(aes(x = forcats::fct_reorder(Function, log2FC), y = log2FC, fill=experiment_phase)) +
  geom_col(position = "dodge") +
  geom_hline(yintercept = 0) +
  coord_flip() +
  theme_classic() +
  labs(
    x = "Microbial Functional Capacity",
    y = "log2FC: 20C vs 10C"
  )
```

#Anti Microbial Resistance
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
 genome_amr <- genome_annotations %>% 
   group_by(genome) %>%
   summarise(AMR = sum(resistance_type == "AMR", na.rm = TRUE), .groups = "drop")
```

#Pre-Treatment AMR Comparisons
```{r amr_per_sample, warning=FALSE, comment="", message=FALSE}
sample_amr_pre <- genome_counts_filt %>%
  mutate(across(-genome, ~ .x / sum(.x, na.rm = TRUE))) %>%
  inner_join(genome_amr, by = "genome") %>%
  pivot_longer(cols = -c(genome, AMR), names_to = "sample", values_to = "rel_abundance") %>%
  group_by(sample) %>%
  summarise(AMR = weighted.mean(AMR, w = rel_abundance, na.rm = TRUE), .groups = "drop") %>%
  left_join(sample_metadata_beta, by = join_by(sample == DNA_datasets)) %>%
  filter(sampling_date <= as.Date("2025-08-30"))

#Top 20 MAGs with highest values
 genome_amr %>%
   left_join(genome_metadata, by = "genome") %>%
   arrange(-AMR) %>%
   head(20) %>%
   tt()

 sample_amr_pre %>%
   group_by(water_temp) %>%
   summarise(mean = mean(AMR, na.rm = T), sd = sd(AMR, na.rm = T)) %>%
   arrange(-mean) %>%
   mutate(AMR = str_c(round(mean, 3), " ± ", round(sd, 3))) %>%
   select(water_temp, AMR) %>% 
   #rename(Temp=1)%>% 
   tt()
```

#Pre-Treatment AMR Plot
```{r}
 sample_amr_pre %>% 
   ggplot(aes(x = water_temp, y = AMR, color = water_temp, fill = water_temp)) +
   geom_jitter(width = 0.2, alpha = 0.7, show.legend = FALSE, size = 0.5) +
   geom_boxplot(width = 0.5, alpha = 0.5, outlier.shape = NA, show.legend = FALSE) +
   scale_color_manual(values = c("10" = "blue","20" = "red")) +
   scale_fill_manual(values = c("10" = "blue","20" = "red")) +
   theme_classic() +
   theme(
 	axis.text = element_text(size = 10), 
 	strip.background = element_blank(), 
 	axis.title.y = element_text(size = 12, margin = margin(t = 0, r = 20, b = 0, l = 0)),
 	axis.title.x = element_blank()
   ) +
   labs(y = "AMR")
```

#Post-Treatment AMR Comparisons
```{r amr_per_sample, warning=FALSE, comment="", message=FALSE}
sample_amr_post <- genome_counts_filt %>%
  mutate(across(-genome, ~ .x / sum(.x, na.rm = TRUE))) %>%
  inner_join(genome_amr, by = "genome") %>%
  pivot_longer(cols = -c(genome, AMR), names_to = "sample", values_to = "rel_abundance") %>%
  group_by(sample) %>%
  summarise(AMR = weighted.mean(AMR, w = rel_abundance, na.rm = TRUE), .groups = "drop") %>%
  left_join(sample_metadata_beta, by = join_by(sample == DNA_datasets)) %>%
  filter(sampling_date >= as.Date("2025-08-30"))

#Top 20 MAGs with highest values
 genome_amr %>%
   left_join(genome_metadata, by = "genome") %>%
   arrange(-AMR) %>%
   head(20) %>%
   tt()

 sample_amr_post %>%
   group_by(water_temp) %>%
   summarise(mean = mean(AMR, na.rm = T), sd = sd(AMR, na.rm = T)) %>%
   arrange(-mean) %>%
   mutate(AMR = str_c(round(mean, 3), " ± ", round(sd, 3))) %>%
   select(water_temp, AMR) %>% 
   #rename(Temp=1)%>% 
   tt()
```

#Post-Treatment AMR Plot
```{r}
 sample_amr_post %>% 
   ggplot(aes(x = water_temp, y = AMR, color = water_temp, fill = water_temp)) +
   geom_jitter(width = 0.2, alpha = 0.7, show.legend = FALSE, size = 0.5) +
   geom_boxplot(width = 0.5, alpha = 0.5, outlier.shape = NA, show.legend = FALSE) +
   scale_color_manual(values = c("10" = "blue","20" = "red")) +
   scale_fill_manual(values = c("10" = "blue","20" = "red")) +
   theme_classic() +
   theme(
 	axis.text = element_text(size = 10), 
 	strip.background = element_blank(), 
 	axis.title.y = element_text(size = 12, margin = margin(t = 0, r = 20, b = 0, l = 0)),
 	axis.title.x = element_blank()
   ) +
   labs(y = "AMR")
```


#Pre/Post Combined Comparison (Overall)
```{r}
sample_amr_combined <- bind_rows(
  sample_amr_pre %>% mutate(experiment_phase = "pre-ABX"),
  sample_amr_post %>% mutate(experiment_phase = "post-ABX"))

 sample_amr_combined %>% 
   ggplot(aes(x = experiment_phase, y = AMR, color = experiment_phase, fill = experiment_phase)) +
   geom_jitter(width = 0.2, alpha = 0.7, show.legend = FALSE, size = 0.5) +
   geom_boxplot(width = 0.5, alpha = 0.5, outlier.shape = NA, show.legend = FALSE) +
   scale_color_manual(values = c("pre-ABX" = "blue","post-ABX" = "red")) +
   scale_fill_manual(values = c("pre-ABX" = "blue","post-ABX" = "red")) +
   theme_classic() +
   theme(
 	axis.text = element_text(size = 10), 
 	strip.background = element_blank(), 
 	axis.title.y = element_text(size = 12, margin = margin(t = 0, r = 20, b = 0, l = 0)),
 	axis.title.x = element_blank()
   ) +
   
   stat_compare_means(method = "wilcox.test", paired = FALSE, p.adjust.method = "BH", label = "p.signif" ) + 
   
   labs(y = "AMR")
```
#Pre/Post Combined Comparison (By Temp)
```{r}
sample_amr_combined <- bind_rows(
  sample_amr_pre %>% mutate(experiment_phase = "pre-ABX"),
  sample_amr_post %>% mutate(experiment_phase = "post-ABX"))

 sample_amr_combined %>% 
   ggplot(aes(x = experiment_phase, y = AMR, color = experimental_group, fill = experimental_group)) +
   geom_jitter(width = 0.2, alpha = 0.7, show.legend = FALSE, size = 0.5) +
   geom_boxplot(width = 0.5, alpha = 0.5, outlier.shape = NA, show.legend = FALSE) +
   theme_classic() +
   theme(
 	axis.text = element_text(size = 10), 
 	strip.background = element_blank(), 
 	axis.title.y = element_text(size = 12, margin = margin(t = 0, r = 20, b = 0, l = 0)),
 	axis.title.x = element_blank()
   ) +
   
   stat_compare_means(method = "kruskal.test", paired = FALSE, p.adjust.method = "BH", label = "p.signif" ) + 
   
   labs(y = "AMR")
```



